export enum ActionType {
  ChangeFilterCategory = 'changeFilterCategory',
  ChangeEstateType = 'changeEstateType',
  ChangeEstateSquare = 'changeEstateSquare',
  ChangeEstateRoom = 'changeEstateRoom',
  ChangeCameraType = 'changeCameraType',
  ChangeCameraResolution = 'changeCameraResolution',
  ChangeCameraVideoResolution = 'changeCameraVideoResolution',
  ChangeLaptopType = 'changeLaptopType',
  ChangeLaptopRam = 'changeLaptopRam',
  ChangeLaptopDiagonal = 'changeLaptopDiagonal',
  ChangeLaptopProcessor = 'changeLaptopProcessor',
  ChangeCarYear = 'changeCarYear',
  ClearState = 'clearState',
}
